server:
  port: 8080

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/courses_records}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:rootroot}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

address:
  user-manager: ${ADDRESS_USER_MANAGER:http://localhost:8060}
  course-manager: ${ADDRESS_COURSE_MANAGER:http://localhost:8070}
  student-manager: ${ADDRESS_STUDENT_MANAGER:http://localhost:8090}
